

const videoUrl = 'https://image.tmdb.org/t/p/w600_and_h900_bestv2';
const token = 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyYTBmOTI2OTYxZDAwYzY2N2UxOTFhMjFjMTQ0NjFmOCIsInN1YiI6IjYwNDYxNTM0MzVhNjFlMDA1YjdjMmZmYiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.LvbdGQ5pvkEgSZY4JkNVIY3g-qF8PRygp7FnacsO1R0';