// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8mD-DybfdUDQz_O9UX_7t9taNpZZHGc0',
    appId: '1:2193910145:web:5985af1c3c997b4e09a080',
    messagingSenderId: '2193910145',
    projectId: 'social-7ec61',
    authDomain: 'social-7ec61.firebaseapp.com',
    storageBucket: 'social-7ec61.appspot.com',
    measurementId: 'G-JT2Y8WMBB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxj0dZy-7BMTJ7eoWrBFkroCeJjgJp9oo',
    appId: '1:2193910145:android:34c507efd5ea5dae09a080',
    messagingSenderId: '2193910145',
    projectId: 'social-7ec61',
    storageBucket: 'social-7ec61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR_6tTFZvWxOjmR9mOo3t2d5ViIjTFSYQ',
    appId: '1:2193910145:ios:5fd12a9785f40fa309a080',
    messagingSenderId: '2193910145',
    projectId: 'social-7ec61',
    storageBucket: 'social-7ec61.appspot.com',
    iosClientId: '2193910145-o3afpm3kdb56r72miadeqql3rbava3ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.pod',
  );
}
